# Generated by Django 5.0.2 on 2024-03-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=200)),
                ('rate', models.CharField(blank=True, max_length=200, null=True)),
                ('extra_per_km', models.CharField(blank=True, max_length=50, null=True)),
                ('day_package', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_img', models.ImageField(upload_to='media/categories/cat_image/%y%m%d/')),
                ('cat_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Journey_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('pick_up_location', models.CharField(max_length=500)),
                ('drop_off_location', models.CharField(max_length=500)),
                ('pick_up_date', models.CharField(max_length=70)),
                ('pick_up_time', models.CharField(max_length=70)),
                ('return_date', models.CharField(max_length=70)),
                ('return_time', models.CharField(max_length=70)),
                ('contact', models.CharField(default='123456789', max_length=20)),
                ('email', models.EmailField(default='email@email.com', max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab_booking_app.car_type')),
                ('journey_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab_booking_app.journey_type')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=100)),
                ('package_name', models.CharField(max_length=200)),
                ('package_day', models.CharField(blank=True, default='1', max_length=200, null=True)),
                ('package_img', models.ImageField(upload_to='media/package/package_image/%y%m%d/')),
                ('description', models.TextField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_booking_app.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('car_img', models.ImageField(blank=True, null=True, upload_to='media/car/car_image/%y%m%d/')),
                ('seat_capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('car_facility', models.CharField(blank=True, choices=[('AC', 'AC'), ('Non AC', 'Non AC')], default='AC', max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('publish', 'publish'), ('draft', 'draft')], max_length=100, null=True)),
                ('bag', models.CharField(blank=True, default='2', max_length=20, null=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_booking_app.car_type')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_booking_app.package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_exclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude_items', models.CharField(blank=True, max_length=300, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_booking_app.package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_include',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_items', models.CharField(blank=True, max_length=300, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_booking_app.package')),
            ],
        ),
    ]
