# Generated by Django 5.0.2 on 2024-03-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=60)),
                ('car_name', models.CharField(max_length=60)),
                ('car_registration', models.FileField(upload_to='media/driver_document/car_registration/%Y-%m-%d')),
                ('driver_license_front', models.FileField(upload_to='media/driver_document/driver_license_front/%Y-%m-%d')),
                ('driver_license_back', models.FileField(upload_to='media/driver_document/driver_license/%Y-%m-%d')),
                ('aadhar_front', models.FileField(upload_to='media/driver_document/aadhar_card/%Y-%m-%d')),
                ('aadhar_back', models.FileField(upload_to='media/driver_document/aadhar_card/%Y-%m-%d')),
                ('car_permit', models.FileField(upload_to='media/driver_document/car_permit/%Y-%m-%d')),
                ('car_insurance', models.FileField(upload_to='media/driver_document/car_insurance/%Y-%m-%d')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
