# Generated by Django 5.0.2 on 2024-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking_app', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
