# Generated by Django 5.0.2 on 2024-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking_app', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
