# Generated by Django 5.0.2 on 2024-03-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking_app', '0007_testimonial_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='journey_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab_booking_app.journey_type'),
        ),
    ]
